

name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]



permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: build
      run: docker build -t ashok .
    - name: tag
      run: docker tag ashok:latest 860423257295.dkr.ecr.us-east-1.amazonaws.com/ashok1:latest
    - name: push
      run: docker push 860423257295.dkr.ecr.us-east-1.amazonaws.com/ashok:latest
    - name: terraform directory
      run : mkdir terraform
    - name: ading file
      run : cp ec2.tf terraform
    - uses: actions/checkout@v3
    - name: creating directory
      run: mkdir hello
    - name: building image
      run: sudo apt-get install unzip
    - name: version
      run : wget https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
    - name: unzip
      run: unzip terraform_1.0.7_linux_amd64.zip
    - name: moving
      run: sudo mv terraform /hello
    - name: version 1
      run: terraform --version
    - name: intializing terraform
      run: terraform init
    - name: building
      run: terraform apply -auto-approve
    

    

   
